name: Run build

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  pull_request_build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn coverage

      - name: Build project
        run: yarn run build
