name: Run build

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  pull_request_build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn coverage

      - name: SonarCloud Scan
        run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.pullrequest.key= ${{ steps.pr.outputs.pull_request_number }}

      - name: Build project
        run: yarn run build
